### ISSUE TITLE
compiling under Windows using Cygwin

### ISSUE THREAD

**Issue by bioSandMan** [dstreett/Super-Deduper#20]
I tried compiling under Windows using Cygwin and received an error:

g++ source/main.cpp source/fileHelper.cpp source/readInfo.cpp source/argCollector.cpp source/fileWriter.cpp source/binarySearch.cpp -O3 -o super_deduper
source/fileHelper.cpp: In member function ‘void FileHelper::FileCheck(char_)’:
source/fileHelper.cpp:25:27: error: ‘access’ was not declared in this scope
     if (access(fName, F_OK)!= -1) {
                           ^
make: *_\* [Makefile:11: build] Error 1

my g++ version is 5.3.0

I was able to fix this by making a change to source file "fileHelper.h". I added "#include <unistd.h>"

That header defines miscellaneous symbolic constants and types. I ran a few test inputs and it seems to work so far and I swear it's faster.

**Comment by dstreett** [comment]
So, I think I just forgot unistd.h in fileHelper.h . I couldn't find any documentation on '#include ' so I think this is a better fix, since man access says it just needs unistd.h .
