### ISSUE TITLE
Typo in help

### ISSUE THREAD

**Issue by samhunter** [dstreett/Super-Deduper#27]
```
    --no-log, N No logfile (outputs to stderr)
```

Missing a '-' before N.

It would also be nice to support '-?' as a synonym to '-h' and '--help'.

**Comment by samhunter** [comment]
It would also be nice if super_deduper was more helpful about how to get help, 

e.g.

Current:
$ ./super_deduper -?
./super_deduper: invalid option -- '?'
This argument is no good ?
 Bad argument :( Exiting            **<--------- Note leading space**

Alternatively:
$ ./super_deduper -?
./super_deduper: invalid argument -- '?', try "--help" for a list of arguments

**Comment by samhunter** [comment]
Usually short-switches are listed first (see for example 'rsync --help', 'bowtie2 --help', etc).

Also additional arguments are traditionally included in "<arg>" instead of "(arg)" .

Current:
        --version, -v Version print  
        --read1-input, -1 Read 1 input (comma sep for multiple files)  
        --read2-input, -2 Read 2 input (comma sep for multiple files)  
        --singleend-input, -U Single end read input (comma sep for multiple files)  
        --tab-input, -T Tab input (comma sep for multiple files)  
        --interleaved-input, -I Interleaved input I (comma sep for multiple files)  
        --stdin-input, -S STDIN input (MUST BE TAB DELIMITED INPUT)  
        --start, -s start location for unique ID (int)  
        --length, -l length of unique ID (int)  
        --quality-check-off, -q Quality Checking Off First Duplicate seen will be kept  
        --gzip-output, -g Output gzipped  
        --interleaved-output, -i Output to interleaved  
        --fastq-output, -f Fastq format outputted (R1 and R2)
        --force, -F Forces overwrite of files
        --tab-output, -t Tab-delimited output
        --to-stdout, -O Prints to STDOUT in Tab Delimited
        --prefix, -P Prefix for outputted files
        --log-file, -L Output-Logfile
        --no-log, N No logfile (outputs to stderr)
        --help, -h Prints help.

Suggested:
-v,  --version, Print version
-1, --read1-input <fastq1,fastq2,...>, Read 1 input (comma sep for multiple files)  
-2, --read2-input <fastq1,fastq2,...>, Read 2 input (comma sep for multiple files)  
-U, --singleend-input <fastq1,fastq2,...>, Single end read input (comma sep for multiple files)  
-T,  --tab-input <tab1,tab2,...>, Tab input (comma sep for multiple files)                                                              

...
-s  --start <int>, 0-based start location for unique ID  
...

**Comment by dstreett** [comment]
Cool! I think I got all that, @samhunter . Let me know if something doesn't look correct.
