### ISSUE TITLE
Total_Time appears to be an int? (Develop)

### ISSUE THREAD

**Issue by samhunter** [dstreett/Super-Deduper#29]
Total_Time in the output doesn't appear to be a float.

**Comment by dstreett** [comment]
I am using second since epoch. It was easy enough to do this, however, I can go down to milli seconds if you would like. What are your thoughts @samhunter ?

**Comment by samhunter** [comment]
Ahh, makes sense. Reads/second is the metric I like best :)

**Comment by dstreett** [comment]
Cool, I can add that metric in as well.
