### ISSUE TITLE
Previous super_deduper version

### ISSUE THREAD

**Issue by madzafv** [dstreett/Super-Deduper#42]
Hello David, 
I'm a PhD student at UCLA.
I'm trying to use my friends program to run some quality control on some whole genome ngs data and his program calls for super_deduper v1.4.
https://github.com/tplinderoth/ngsQC/tree/master/readCleaner
I tried to run with the most recent release of super_deduper but It seems like his scripts are pretty sensitive to that.

Would you mind sharing  super_deduper v1.4 qith me?
Thank you,
Madza Farias-Virgens

**Comment by samhunter** [comment]
I think you should be able to access it from the git clone by doing something like:
1) git clone the super-deduper repository
2) git checkout 177fd62b1a018cbffc9e0aaeb76b136f660e8ad0

Then build the package as normal.

I'm guessing that there might be some minor differences in command line switches that are causing the problems you are running into? I would strongly encourage you to switch to the latest release and modify your readCleaner script but, up to you.
